"""empty message

Revision ID: f552e0afad07
Revises: 51e4da1b9906
Create Date: 2020-05-08 22:42:44.389494

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f552e0afad07'
down_revision = '51e4da1b9906'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('create_time', sa.DateTime(), nullable=True))
    op.drop_column('question', 'crete_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('crete_time', mysql.DATETIME(), nullable=True))
    op.drop_column('question', 'create_time')
    # ### end Alembic commands ###
